config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "mysamtool.com"

  devise_for :users
  root 'pages#home'

  namespace :control_room do
  	resources :ideation_and_selection_overviews do
      member do
        post :toggle_status
        post :increment_pos
        post :decrement_pos
      end
    end

    get '/hit-lists', to: 'dashboard#hitlists', as: :hitlists

  	resources :statistic_overviews do
      member do
        post :toggle_status
        post :increment_pos
        post :decrement_pos
      end
    end

    resources :blogs do
      get :settings, to: 'blogs#settings', as: :settings

      member do
        post :toggle_status
        post :increment_pos
        post :decrement_pos
        get 'statistics-overview', to: 'blogs#statistics', as: :statistic_overview
        post :process_spreadsheet, to: 'blogs#process_spreadsheet', as: :process_spreadsheet
      end
      resources :brand_plan_categories do
        member do
          post :toggle_status
          post :increment_pos
          post :decrement_pos
        end
      end
      resources :posts do
        member do
          post :toggle_status
          post :increment_pos
          post :decrement_pos
        end
      end
      resources :potential_posts do
        collection do
          get :filter
        end
        member do
          post :toggle_status
          post :increment_pos
          post :decrement_pos
        end
      end
    end

    get '/', to: 'dashboard#index'
  end

end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  after_create :create_statistic_overview

  # acts_as_list
  ADDABLE     = true
  EDITABLE    = true
  VIEWABLE    = true
  PUBLISHABLE = false
  DELETEABLE  = true

  belongs_to :user

  has_many :posts, dependent: :destroy
  has_many :brand_plan_categories, dependent: :destroy
  has_many :potential_posts, dependent: :destroy
  has_many :blog_spreadsheet_imports, dependent: :destroy
  has_one :statistic_overview, dependent: :destroy

  default_scope { order(position: :asc) }

  def label
    "#{name}"
  end

  def sublabel
    ""
  end

  def writing_hours_left_on_hit_list
    pillar_hours = 0
    response_hours = 0
    staple_hours = 0
    self.posts.not_published.each do |post|
      response_hours += 1.5 if post.post_type == 'response'
      staple_hours += 3 if post.post_type == 'staple'
      pillar_hours += 4.5 if post.post_type == 'pillar'
    end
    total_hours = response_hours + staple_hours + pillar_hours

    { response: response_hours, staple: staple_hours, pillar: pillar_hours, total: total_hours }
  end

  def total_num_words_left_to_be_written
    num_words = 0
    self.posts.not_published.each do |post|
      num_words += 1350 if post.post_type == 'response'
      num_words += 2500 if post.post_type == 'staple'
      num_words += 3500 if post.post_type == 'pillar'
    end

    num_words
  end

  def num_potential_posts
    num = 0
    self.brand_plan_categories.each do |category|
      num += category.estimated_number_of_possible_posts
    end
    num
  end

  private
  def create_statistics_overview
    self.statistics_overview = StatisticOverview.create(blog_id: self.id)
  end
end

app/models/control_room.rb
module ControlRoom
  def self.table_name_prefix
    'control_room_'
  end
end

app/models/control_room/section.rb
class ControlRoom::Section < ApplicationRecord
end

app/controllers/control_room/application_controller.rb
module ControlRoom
  class ApplicationController < ActionController::Base
    layout 'control_room/application'
    before_action :authenticate_user!

    protected

    def is_administrator?
      unless current_cms_user.administrator?
        flash[:danger] = 'You are not authorized to perform that action.'
        redirect_back fallback_location: control_room_path
        return false
      end
      true
    end
  end
end

app/controllers/control_room/blogs_controller.rb
class ControlRoom::BlogsController < ControlRoom::ElementsController

  def element_model
    Blog
  end

  def index
    @items = current_user.blogs
  end

  def show
    super
    @imports = @item.blog_spreadsheet_imports
    @posts = @item.posts.order_of_priority
  end

  def create
    @item = element_model.new element_params
    current_user.blogs << @item

    if @item.save
      flash[:success] = "Successfully created #{element_model.to_s}"
      redirect_to action: "show", id: @item
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  def statistics
    @item = current_user.blogs.friendly.find(params[:id])
    @posts = @item.posts
    @writing_hours_left = @item.writing_hours_left_on_hit_list
    @words_left = @item.total_num_words_left_to_be_written
    @brand_plan_categories_count = @item.num_potential_posts
  end

  def settings
    @item = current_user.blogs.friendly.find(params[:blog_id])
    @spreadsheet = BlogSpreadsheetImport.new
  end

  def process_spreadsheet
    @item = current_user.blogs.friendly.find(params[:id])
    @spreadsheet = BlogSpreadsheetImport.new spreadsheet_params
    if @spreadsheet.save 
      @item.blog_spreadsheet_imports << @spreadsheet
      
      flash[:success] = "We've placed your excel sheet in a queue. Please give it a minute or two to process all of your data"
      redirect_to control_room_blog_path(id: @item.id)
    else
      flash[:danger] = @spreadsheet.errors.full_messages.to_sentence
      render :settings
    end 
  end

  protected

  def spreadsheet_params
    params.require(:blog_spreadsheet_import).permit(:blog_id, :spreadsheet)
  end

  def set_item
    @item = current_user.blogs.friendly.find(params[:id])
  end

end

app/controllers/control_room/brand_plan_categories_controller.rb
class ControlRoom::BrandPlanCategoriesController < ControlRoom::ElementsController

  def element_model
    BrandPlanCategory
  end

  def index
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @items = @blog.brand_plan_categories
  end

  def new
    @item = element_model.new
    @blog = current_user.blogs.friendly.find(params[:blog_id])
  end

  def create
    @item = current_user.blogs.friendly.find(params[:blog_id]).brand_plan_categories.build element_params

    if @item.save
      respond_to do |format|
        format.html {
          flash[:success] = "Successfully created #{element_model.to_s}"
          redirect_to action: "show", id: @item
        }
        format.js
      end
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  protected

  def set_item
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @item = @blog.brand_plan_categories.friendly.find(params[:id])
  end

end

app/controllers/control_room/dashboard_controller.rb
module ControlRoom
  class DashboardController < ControlRoom::ApplicationController

    def hitlists
      @blogs = current_user.blogs.includes(:posts)
    end
    
  end
end

app/controllers/control_room/elements_controller.rb
class ControlRoom::ElementsController < ControlRoom::ApplicationController
  helper_method :element_model
  before_action :set_item_name, only: [:show, :index, :new, :edit]
  before_action :set_item, only: [:show, :edit, :update, :destroy, :toggle_status]
  # before_action :authorize_cms_user

  def index
    @items = element_model.all
  end

  def new
    @item = element_model.new
  end

  def create
    @item = element_model.new element_params

    if @item.save
      respond_to do |format|
        format.html {
          flash[:success] = "Successfully created #{element_model.to_s}"
          redirect_to action: "show", id: @item
        }
        format.js
      end
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  def edit
  end

  def update
    if @item.update element_params
      flash[:success] = "Successfully updated #{element_model.to_s}"
      redirect_to action: "show", id: @item
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: :edit, controller: element_model.to_s.pluralize.underscore
    end
  end

  def show
  end

  def destroy
    if @item.destroy
      respond_to do |format|
        format.html {
          flash[:success] = "Successfully deleted #{element_model.to_s}"
          redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
        }

        format.js
      end
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  def toggle_status
    @item.toggle_status
    redirect_back(fallback_location: control_room_path)
  end

  def increment_pos
    @item = element_model.friendly.find(params[:id])
    @item.move_higher
    redirect_back(fallback_location: control_room_path)
  end

  def decrement_pos
    @item = element_model.friendly.find(params[:id])
    @item.move_lower
    redirect_back(fallback_location: control_room_path)
  end

  protected

  def set_item
    @item = element_model.friendly.find(params[:id])
  end

  def authorize_cms_user
    section = ControlRoom::Section.find_by_controller(controller_name)
    unless current_cms_user.sections.include?(section) || current_cms_user.administrator?
      flash[:danger] = "You do not have access to the #{controller_name.pluralize}.
                        Please contact an administrator if you need help."
      redirect_to control_room_path
    end
  end

  def element_params 
    params.require("#{element_model.to_s.underscore}").permit!
  end

  def set_item_name
    @item_name = element_model.to_s
  end
end

app/controllers/control_room/posts_controller.rb
class ControlRoom::PostsController < ControlRoom::ElementsController

  def element_model
    Post
  end

  def index
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @items = @blog.posts.page(params[:page]).per(20)
  end

  def new
    super
    @blog = current_user.blogs.friendly.find(params[:blog_id])
  end

  protected

  def set_item
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @item = @blog.posts.friendly.find(params[:id])
  end

end

app/controllers/control_room/potential_posts_controller.rb
class ControlRoom::PotentialPostsController < ControlRoom::ElementsController

  def element_model
    PotentialPost
  end

  def index
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @items = @blog.potential_posts
  end

  def filter
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @items = @blog.potential_posts

    begin
      if !(params[:competition].empty?) && !(params[:competition] == 'No Filter')
        @items = @items.by_competition(params[:competition].titleize.gsub(' ', '').underscore)
      end
  
      if !(params[:will_create].empty?) && !(params[:will_create] == 'No Filter')
        @items = @items.by_will_create(params[:will_create].titleize.gsub(' ', '').underscore)
      end
    rescue => exception
      puts "FILTER ERROR: Potential Posts #{exception}"  
    end

    render partial: 'control_room/stimulus/quick_element', locals: { items: @items }
  end

  def new
    super
    @blog = current_user.blogs.friendly.find(params[:blog_id])
  end

  def create
    @item = current_user.blogs.friendly.find(params[:blog_id]).potential_posts.build(element_params)

    if @item.save
      respond_to do |format|
        format.html {
          flash[:success] = "Successfully created #{element_model.to_s}"
          redirect_to action: "show", id: @item
        }
        format.js
      end
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  def destroy
    if @item.destroy
      respond_to do |format|
        format.html {
          flash[:success] = "Successfully deleted #{element_model.to_s}"
          redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
        }

        format.js
      end
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  protected

  def set_item
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @item = @blog.potential_posts.friendly.find(params[:id])
  end

end

app/controllers/control_room/statistic_overviews_controller.rb
class ControlRoom::StatisticOverviewsController < ControlRoom::ElementsController

  def element_model
    StatisticOverview
  end

end

app/views/control_room/blogs/_content.html.erb
<div class='float-right'>
  <%= link_to fa_icon('cog'), control_room_blog_settings_path(@item), class: 'btn btn-circle btn-secondary btn-md' %>
  <% if element_model::EDITABLE %>
    <%= link_to fa_icon('edit'), {action: :edit, id: @item }, class: 'btn btn-circle btn-info btn-md' %>
  <% end %>

  <% if element_model::DELETEABLE %>
    <%= link_to fa_icon('trash'), {action: "destroy", id: @item }, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-circle btn-danger btn-md' %>
  <% end %>
</div>

<% @imports.each do |import| %>
  <% if import.custom_errors != nil %>
    <%= import.custom_errors %>
  <% end %>
<% end %>

<p class='lead'>Here are the posts you should work on...</p>

<% @posts.each do |post| %>
  <ul>
    <li><%= post.title.titleize %></li>
  </ul>
<% end %>

app/views/control_room/blogs/_form.html.erb
<%= f.input :name %>

app/views/control_room/blogs/settings.html.erb
<h1>Settings for <%= @item.name.titleize %></h1>

<h3 class='mt-5'>Excel Upload</h3>
<div class='upload card'>
  <div class='card-body'>
    <p>You can upload an Excel sheet (.xlsx) to pre fill out all your blog info when you create a new blog using S.A.M.<br>
    Just make sure it has the same structure has the base excel file. If you added any new columns they will be ignored.<br>
    But if you completely changed the structure of the excel sheets, it's not going to import correctly.</p>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#blogSpreadsheetImport">
      <%= fa_icon('upload', text: 'Upload') %>
    </button>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="blogSpreadsheetImport" tabindex="-1" role="dialog" aria-labelledby="blogSpreadsheetImportTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="blogSpreadsheetImportTitle">Upload an Excel Sheet</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @spreadsheet, url: process_spreadsheet_control_room_blog_path(@item) do |f| %>
          <%= f.association :blog, collection: current_user.blogs, selected: @blog %>

          <%= f.input :spreadsheet, input_html: { class: 'form-control-file' } %>

          <%= f.submit 'Upload', class: 'btn btn-md btn-primary'%>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/control_room/blogs/show.html.erb
<h2 class='float-left'><%= @item.label.titleize %></h2>

<div class='float-right'>
  <%= link_to fa_icon('crosshairs', text: 'Hit List'), control_room_blog_posts_path(@item), class: 'btn btn-md btn-secondary'%>
  <%= link_to fa_icon('lightbulb', text: 'Ideation & Selection'), control_room_blog_potential_posts_path(@item), class: 'btn btn-md btn-primary' %>
  <%= link_to fa_icon('box', text: 'Brand Plan'), control_room_blog_brand_plan_categories_path(@item), class: 'btn btn-md btn-info' %>
  <%= link_to fa_icon('clipboard', text: 'Statistics'), {action: :statistics, id: @item.id}, class: 'btn btn-md btn-warning', id: :statistics_button %>
  
  <% if element_model::PUBLISHABLE %>
    <% if @item.unpublished? %>
      <%= link_to fa_icon('upload', text: "Publish #{@item_name.titleize.singularize}"), {action: :toggle_status }, data: { confirm: 'Are you sure?' }, method: :post, class: 'btn btn-success btn-md' %>
    <% else %>
      <%= link_to fa_icon('upload', text: "Unpublish #{@item_name.titleize.singularize}"), {action: :toggle_status }, data: { confirm: 'Are you sure?' }, method: :post, class: 'btn btn-success btn-md' %>
    <% end %>
  <% end %>
</div>

<hr class='fix-float'>

<%= render 'content' %>

app/views/control_room/blogs/statistics.html.erb
<h2 class='float-left'>Statistics Overview</h2>

<div class='float-right'>
  <%= link_to fa_icon('newspaper', text: 'Blog'), control_room_blog_path(@item), class: 'btn btn-success btn-md' %>
</div>

<hr class='fix-float'>

<h3><strong>SNAPSHOT</strong> <em>(Include all these data when posting in the community.)</em></h3>

<div class='row mt-4'>
  <div class='col-lg-6'>
    <div class="card border-primary mb-3">
      <div class="card-header"><strong>Total Number of Posts Published</strong></div>
      <div class="card-body text-primary">
        <canvas id="total_posts_published"></canvas>
      </div>
    </div>
  </div>
</div>

<div class='row mt-3'>
  <div class='col-lg-6'>
    <div class="card border-primary mb-3">
      <div class="card-header"><strong>Age of Posts (in months).</strong></div>
      <div class="card-body text-primary">
        <canvas id="age_of_posts"></canvas>
      </div>
    </div>
  </div>
  <div class='col-lg-6'>
    <div class="card border-primary mb-3">
      <div class="card-header"><strong>Posts Published (completed) by Type</strong></div>
      <div class="card-body text-primary">
        <canvas id="posts_published_by_type"></canvas>
      </div>
    </div>
  </div>
</div>

<!-- COMMITMENT REQUIRED -->

<hr>
<h3><strong>Commitment Required</strong></h3>
<div class='row mt-4'>
  <div class='col-lg-8'>
    <div class="card border-primary mb-3">
      <div class="card-header"><strong>Approx Writing Hours Left for Posts by Type in Hours. (TOTAL: <%= @writing_hours_left[:total] %> hours)</strong></div>
      <div class="card-body text-primary">
        <canvas id="writing_hours_left"></canvas>
      </div>
    </div>
  </div>  
  <div class='col-lg-4'>
    <div class="card border-primary mb-3">
      <div class="card-header"><strong>Words Left and Pricing Info</strong></div>
      <div class="card-body text-primary">
        <strong>Total Approx Words Left in Hit list: </strong><br> <%= number_with_delimiter(@words_left) %>
        <hr>
        <strong>Cost of remaining Hit List @ 3 cents per word: </strong><br> <%= number_to_currency(@words_left * 0.03) %>
        <hr>
        <strong>Cost to purchase 10 posts of each post type: </strong><br>
        <%= number_to_currency(((10*1350)+(10*2500)+(10*3500))*0.03) %>
      </div>
    </div>
  </div>
</div>

<!-- Hit List Statistics -->
<hr>
<div class='row'>
  <div class='col-lg-6'>
    <h3><strong>Hit List Statistics</strong></h3>

    <div class='row mt-4'>
      <div class='col-lg-12'>
        <div class="card border-primary mb-3">
          <div class="card-header"><strong>All Posts in Hit List by Type (TOTAL: <%= @posts.count %>)</strong></div>
          <div class="card-body text-primary">
            <canvas id="posts_in_hit_list"></canvas>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class='col-lg-6'>
    <h3><strong>Completion Rate</strong></h3>
    <div class='row mt-4'>
      <div class='col-lg-12'>
        <div class="card border-primary mb-3">
          <div class="card-header"><strong>INCOMPLETE Posts in Hit List by Type (TOTAL: <%= @posts.not_published.count %>)</strong></div>
          <div class="card-body text-primary">
            <canvas id="incomplete_posts_in_hit_list"></canvas>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<hr>
<h3><strong>Content Age</strong></h3>

<div class='row mt-4'>
  <div class='col-lg-8'>
    <div class="card border-primary mb-3">
      <div class="card-header"><strong>Posts Published that are Older than a Certain Time.</strong></div>
      <div class="card-body text-primary">
        <canvas id="content_age_for_all_posts"></canvas>
      </div>
    </div>
  </div>
  <div class='col-lg-4'>
    <div class='row'>
      <div class='col-lg-12'>
        <div class="card border-primary mb-3">
          <div class="card-header"><strong>Breakdown by post type with publish date older than 35 weeks.</strong></div>
          <div class="card-body text-primary">
            <canvas id="content_age_for_all_posts_by_type"></canvas>
          </div>
        </div>
      </div>

      <div class='col-lg-12'>
        <hr>
        <h3>Brand Plan</h3>
        <div class="card border-primary mb-3">
          <div class="card-header"><strong>Brand Plan Overview</strong></div>
          <div class="card-body text-primary">
            <strong># of Possible Posts: </strong> <br><%= @brand_plan_categories_count %>

            <hr>

            <strong>Percentage of Brand Plan Complete: </strong> <br>
            <% if @brand_plan_categories_count != 0 %>
              <%= ((@posts.published.count.to_f / @brand_plan_categories_count.to_f) * 100).round(2) %>%
            <% else %>
              Can't Calculate due to division by 0
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  var options = {
    scales: {
      yAxes: [{
        ticks: {
            beginAtZero: true
        }
      }]
    },
    plugins: {
      datalabels: {
        color: '#fff'
      }
    }
  }

  var ctx = document.getElementById('content_age_for_all_posts_by_type').getContext('2d');  
  new Chart(ctx, {
    type: 'polarArea',
    data: {
      labels: ['Response Posts', 'Staple Posts', 'Pillar Posts'],
      datasets: [{
        data: [
          <%= @posts.published.posts_for_type(:response).older_than(35.weeks.ago).count %>,
          <%= @posts.published.posts_for_type(:staple).older_than(35.weeks.ago).count %>,
          <%= @posts.published.posts_for_type(:staple).older_than(35.weeks.ago).count %>,
        ],
        backgroundColor: [
          'rgba(231, 76, 60, 0.55)',
          'rgba(46, 204, 113, 0.55)',
          'rgba(52, 152, 219, 0.55)'
        ]
      }]
    },
    options: options
  });  
    
  var ctx = document.getElementById('content_age_for_all_posts').getContext('2d');
  var myBarChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: [
        '7 Days',
        '30 Days',
        '60 Days (2 months)',
        '90 Days (3 months)',
        '120 Days (4 months)',
        '150 Days (5 months)',
        '180 Days (6 months)',
        '210 Days (7 months)',
        '240 Days (8 months)'
      ],
      datasets: [{
        label: 'Posts published that are older than a certain time (# of posts)',
        data: [
          <%= @posts.published.older_than(7.day.ago).count %>,
          <%= @posts.published.older_than(30.day.ago).count %>,
          <%= @posts.published.older_than(60.day.ago).count %>,
          <%= @posts.published.older_than(90.day.ago).count %>,
          <%= @posts.published.older_than(120.day.ago).count %>,
          <%= @posts.published.older_than(150.day.ago).count %>,
          <%= @posts.published.older_than(180.day.ago).count %>,
          <%= @posts.published.older_than(210.day.ago).count %>,
          <%= @posts.published.older_than(240.day.ago).count %>,
        ],
        backgroundColor: [
          'rgba(155, 89, 182, 0.55)',
          'rgba(52, 152, 219, 0.55)',
          'rgba(46, 204, 113, 0.55)',
          'rgba(26, 188, 156, 0.55)',
          'rgba(241, 196, 15, 0.55)',
          'rgba(230, 126, 34, 0.55)',
          'rgba(231, 76, 60, 0.55)',
          'rgba(155, 89, 182, 0.55)',
          'rgba(52, 73, 94, 0.55)'
        ]
      }]
    },
    options: options
  });

  var ctx = document.getElementById('incomplete_posts_in_hit_list').getContext('2d');
  var myPieChart = new Chart(ctx, {
      type: 'pie',
      data: {
        labels: ['Response Posts', 'Staple Posts', 'Pillar Posts'],
        datasets: [{
          data: [
            <%= @posts.incomplete_for_type(:response).count %>,
            <%= @posts.incomplete_for_type(:staple).count %>,
            <%= @posts.incomplete_for_type(:pillar).count %>,
          ],
          backgroundColor: [
            'rgba(26, 188, 156, 0.55)',
            'rgba(231, 76, 60, 0.55)',
            'rgba(155, 89, 182, 0.55)'
          ]
        }]
      },
      options: options
  });

  var ctx = document.getElementById('posts_in_hit_list').getContext('2d');
  var myPieChart = new Chart(ctx, {
      type: 'pie',
      data: {
        labels: ['Response Posts', 'Staple Posts', 'Pillar Posts'],
        datasets: [{
          data: [
            <%= @posts.posts_for_type(:response).count %>,
            <%= @posts.posts_for_type(:staple).count %>,
            <%= @posts.posts_for_type(:pillar).count %>,
          ],
          backgroundColor: [
            'rgba(26, 188, 156, 0.55)',
            'rgba(231, 76, 60, 0.55)',
            'rgba(155, 89, 182, 0.55)'
          ]
        }]
      },
      options: options
  });

  var ctx = document.getElementById('writing_hours_left').getContext('2d');
  var myBarChart = new Chart(ctx, {
    type: 'bar',
    data: {
      labels: ['Approx Writing Hours Left For Response Posts', 'Approx Writing Hours Left For Staple Posts', 'Approx Writing Hours Left For Pillar Posts'],
      datasets: [{
        label: 'Approx Writing Hours Left for Posts by Type (in hours)',
        data: [
          <%= @writing_hours_left[:response] %>,
          <%= @writing_hours_left[:staple] %>,
          <%= @writing_hours_left[:pillar] %>
        ],
        backgroundColor: [
          'rgba(230, 126, 34, 0.55)',
          'rgba(46, 204, 113, 0.55)',
          'rgba(155, 89, 182, 0.55)'
        ]
      }]
    },
    options: options
  });

  var ctx = document.getElementById('posts_published_by_type').getContext('2d');
  var myPieChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ['Response Posts Published', 'Staple Posts Published', 'Pillar Posts Published'],
        datasets: [{
          label: 'Posts Published by Type (# of posts)',
          data: [
            <%= @posts.completed_for_type(:response).count %>, 
            <%= @posts.completed_for_type(:staple).count %>,
            <%= @posts.completed_for_type(:pillar).count %>
          ],
          backgroundColor: [
            'rgba(231, 76, 60, 0.55)',
            'rgba(46, 204, 113, 0.55)',
            'rgba(52, 152, 219, 0.55)'
          ]
        }],
      },
    options: options
  });

  var ctx = document.getElementById('age_of_posts').getContext('2d');
  var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ['1 Month or Less', '2 Months', '3 Months', '4 Months', '5 Months', '6 Months', '7 Months', '8 months or more'],
        datasets: [{
          label: 'Age of Posts (in months)',
          data: [
            <% 7.times do |i| %>
              <%= @posts.published.old_in_months((i+1)).count %>,
            <% end %>
            <%= @posts.published.older_than(8.months.ago).count %>
          ],
          backgroundColor: [
            'rgba(231, 76, 60,0.55)',
            'rgba(230, 126, 34,0.55)',
            'rgba(241, 196, 15,0.55)',
            'rgba(46, 204, 113,0.55)',
            'rgba(26, 188, 156,0.55)',
            'rgba(52, 152, 219,0.55)',
            'rgba(155, 89, 182,0.55)',
            'rgba(52, 73, 94,0.55)'
          ],
          borderWidth: 1
        }]
      },
      options: options
  });

  var ctx = document.getElementById('total_posts_published').getContext('2d');
  var myPieChart = new Chart(ctx, {
    type: 'pie',
    data: {
      labels: ["Published", "Not Published"],
      datasets: [{
        data: [
          <%= @posts.published.count %>,
          <%= @posts.not_published.count %>
        ],
        backgroundColor: [
          'rgba(46, 204, 113, 0.55)',
          'rgba(149, 165, 166, 0.55)'
        ]
      }]
    },
    options: options
});
</script>