config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "mysamtool.com"

  devise_for :users
  root 'pages#home'

  namespace :control_room do
  	resources :ideation_and_selection_overviews do
      member do
        post :toggle_status
        post :increment_pos
        post :decrement_pos
      end
    end

    get '/hit-lists', to: 'dashboard#hitlists', as: :hitlists

  	resources :statistic_overviews do
      member do
        post :toggle_status
        post :increment_pos
        post :decrement_pos
      end
    end

    resources :blogs do
      get :settings, to: 'blogs#settings', as: :settings

      member do
        post :toggle_status
        post :increment_pos
        post :decrement_pos
        get 'statistics-overview', to: 'blogs#statistics', as: :statistic_overview
        post :process_spreadsheet, to: 'blogs#process_spreadsheet', as: :process_spreadsheet
      end
      resources :brand_plan_categories do
        member do
          post :toggle_status
          post :increment_pos
          post :decrement_pos
        end
      end
      resources :posts do
        member do
          post :toggle_status
          post :increment_pos
          post :decrement_pos
        end
      end
      resources :potential_posts do
        collection do
          get :filter
        end
        member do
          post :toggle_status
          post :increment_pos
          post :decrement_pos
        end
      end
    end

    get '/', to: 'dashboard#index'
  end

end

app/models/control_room.rb
module ControlRoom
  def self.table_name_prefix
    'control_room_'
  end
end

app/models/control_room/section.rb
class ControlRoom::Section < ApplicationRecord
end

app/controllers/control_room/application_controller.rb
module ControlRoom
  class ApplicationController < ActionController::Base
    layout 'control_room/application'
    before_action :authenticate_user!

    protected

    def is_administrator?
      unless current_cms_user.administrator?
        flash[:danger] = 'You are not authorized to perform that action.'
        redirect_back fallback_location: control_room_path
        return false
      end
      true
    end
  end
end

app/controllers/control_room/blogs_controller.rb
class ControlRoom::BlogsController < ControlRoom::ElementsController

  def element_model
    Blog
  end

  def index
    @items = current_user.blogs
  end

  def show
    super
    @imports = @item.blog_spreadsheet_imports
    @posts = @item.posts.order_of_priority
  end

  def create
    @item = element_model.new element_params
    current_user.blogs << @item

    if @item.save
      flash[:success] = "Successfully created #{element_model.to_s}"
      redirect_to action: "show", id: @item
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  def statistics
    @item = current_user.blogs.friendly.find(params[:id])
    @posts = @item.posts
    @writing_hours_left = @item.writing_hours_left_on_hit_list
    @words_left = @item.total_num_words_left_to_be_written
    @brand_plan_categories_count = @item.num_potential_posts
  end

  def settings
    @item = current_user.blogs.friendly.find(params[:blog_id])
    @spreadsheet = BlogSpreadsheetImport.new
  end

  def process_spreadsheet
    @item = current_user.blogs.friendly.find(params[:id])
    @spreadsheet = BlogSpreadsheetImport.new spreadsheet_params
    if @spreadsheet.save 
      @item.blog_spreadsheet_imports << @spreadsheet
      
      flash[:success] = "We've placed your excel sheet in a queue. Please give it a minute or two to process all of your data"
      redirect_to control_room_blog_path(id: @item.id)
    else
      flash[:danger] = @spreadsheet.errors.full_messages.to_sentence
      render :settings
    end 
  end

  protected

  def spreadsheet_params
    params.require(:blog_spreadsheet_import).permit(:blog_id, :spreadsheet)
  end

  def set_item
    @item = current_user.blogs.friendly.find(params[:id])
  end

end

app/controllers/control_room/brand_plan_categories_controller.rb
class ControlRoom::BrandPlanCategoriesController < ControlRoom::ElementsController

  def element_model
    BrandPlanCategory
  end

  def index
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @items = @blog.brand_plan_categories
  end

  def new
    @item = element_model.new
    @blog = current_user.blogs.friendly.find(params[:blog_id])
  end

  def create
    @item = current_user.blogs.friendly.find(params[:blog_id]).brand_plan_categories.build element_params

    if @item.save
      respond_to do |format|
        format.html {
          flash[:success] = "Successfully created #{element_model.to_s}"
          redirect_to action: "show", id: @item
        }
        format.js
      end
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  protected

  def set_item
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @item = @blog.brand_plan_categories.friendly.find(params[:id])
  end

end

app/controllers/control_room/dashboard_controller.rb
module ControlRoom
  class DashboardController < ControlRoom::ApplicationController

    def hitlists
      @blogs = current_user.blogs.includes(:posts)
    end
    
  end
end

app/controllers/control_room/elements_controller.rb
class ControlRoom::ElementsController < ControlRoom::ApplicationController
  helper_method :element_model
  before_action :set_item_name, only: [:show, :index, :new, :edit]
  before_action :set_item, only: [:show, :edit, :update, :destroy, :toggle_status]
  # before_action :authorize_cms_user

  def index
    @items = element_model.all
  end

  def new
    @item = element_model.new
  end

  def create
    @item = element_model.new element_params

    if @item.save
      respond_to do |format|
        format.html {
          flash[:success] = "Successfully created #{element_model.to_s}"
          redirect_to action: "show", id: @item
        }
        format.js
      end
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  def edit
  end

  def update
    if @item.update element_params
      flash[:success] = "Successfully updated #{element_model.to_s}"
      redirect_to action: "show", id: @item
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: :edit, controller: element_model.to_s.pluralize.underscore
    end
  end

  def show
  end

  def destroy
    if @item.destroy
      respond_to do |format|
        format.html {
          flash[:success] = "Successfully deleted #{element_model.to_s}"
          redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
        }

        format.js
      end
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  def toggle_status
    @item.toggle_status
    redirect_back(fallback_location: control_room_path)
  end

  def increment_pos
    @item = element_model.friendly.find(params[:id])
    @item.move_higher
    redirect_back(fallback_location: control_room_path)
  end

  def decrement_pos
    @item = element_model.friendly.find(params[:id])
    @item.move_lower
    redirect_back(fallback_location: control_room_path)
  end

  protected

  def set_item
    @item = element_model.friendly.find(params[:id])
  end

  def authorize_cms_user
    section = ControlRoom::Section.find_by_controller(controller_name)
    unless current_cms_user.sections.include?(section) || current_cms_user.administrator?
      flash[:danger] = "You do not have access to the #{controller_name.pluralize}.
                        Please contact an administrator if you need help."
      redirect_to control_room_path
    end
  end

  def element_params 
    params.require("#{element_model.to_s.underscore}").permit!
  end

  def set_item_name
    @item_name = element_model.to_s
  end
end

app/controllers/control_room/posts_controller.rb
class ControlRoom::PostsController < ControlRoom::ElementsController

  def element_model
    Post
  end

  def index
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @items = @blog.posts.page(params[:page]).per(20)
  end

  def new
    super
    @blog = current_user.blogs.friendly.find(params[:blog_id])
  end

  protected

  def set_item
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @item = @blog.posts.friendly.find(params[:id])
  end

end

app/controllers/control_room/potential_posts_controller.rb
class ControlRoom::PotentialPostsController < ControlRoom::ElementsController

  def element_model
    PotentialPost
  end

  def index
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @items = @blog.potential_posts
  end

  def filter
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @items = @blog.potential_posts

    begin
      if !(params[:competition].empty?) && !(params[:competition] == 'No Filter')
        @items = @items.by_competition(params[:competition].titleize.gsub(' ', '').underscore)
      end
  
      if !(params[:will_create].empty?) && !(params[:will_create] == 'No Filter')
        @items = @items.by_will_create(params[:will_create].titleize.gsub(' ', '').underscore)
      end
    rescue => exception
      puts "FILTER ERROR: Potential Posts #{exception}"  
    end

    render partial: 'control_room/stimulus/quick_element', locals: { items: @items }
  end

  def new
    super
    @blog = current_user.blogs.friendly.find(params[:blog_id])
  end

  def create
    @item = current_user.blogs.friendly.find(params[:blog_id]).potential_posts.build(element_params)

    if @item.save
      respond_to do |format|
        format.html {
          flash[:success] = "Successfully created #{element_model.to_s}"
          redirect_to action: "show", id: @item
        }
        format.js
      end
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  def destroy
    if @item.destroy
      respond_to do |format|
        format.html {
          flash[:success] = "Successfully deleted #{element_model.to_s}"
          redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
        }

        format.js
      end
    else
      flash[:danger] = @item.errors.full_messages.to_sentence
      redirect_to action: "index", controller: element_model.to_s.pluralize.underscore
    end
  end

  protected

  def set_item
    @blog = current_user.blogs.friendly.find(params[:blog_id])
    @item = @blog.potential_posts.friendly.find(params[:id])
  end

end

app/controllers/control_room/statistic_overviews_controller.rb
class ControlRoom::StatisticOverviewsController < ControlRoom::ElementsController

  def element_model
    StatisticOverview
  end

end

app/views/control_room/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/control_room/shared/_footer.html.erb
<!-- Footer -->
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Control Room 2019</span>
    </div>
  </div>
</footer>
<!-- End of Footer -->

app/views/control_room/shared/_sidebar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= control_room_path %>">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-robot"></i>
    </div>
    <div class="sidebar-brand-text mx-3" style='position: relative;'>S.A.M<br><small style='position:absolute;top:-10px;right:-25px;'><span class='badge badge-danger'>Beta</span></small></div>
  </a>
  <li class='text-white text-center mb-3'><small>For the bloggers at Project 24</small></li>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="<%= control_room_path %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Sections
  </div>

  <% ControlRoom::Section.all.each do |section| %>
    <li class="nav-item">
      <a class="nav-link" href="<%= url_for(controller: section.controller, action: 'index') %>">
        <%= fa_icon(section.icon) %>
        <span><%= section.title %></span></a>
    </li>
  <% end %>

  <li class="nav-item">
    <a class="nav-link" href="<%= control_room_hitlists_path %>">
      <%= fa_icon('crosshairs') %>
      <span>Hit Lists</span></a>
  </li>

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline mt-5">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>
<!-- End of Sidebar -->

app/views/control_room/shared/_topbar.html.erb
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Topbar Search -->
  <!-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form> -->

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    
    <!-- Nav Item - Alerts -->
    <%# <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        <span class="badge badge-danger badge-counter">3+</span>
      </a>
      <!-- Dropdown - Alerts -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
          Alerts Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-primary">
              <i class="fas fa-file-alt text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly report is ready to download!</span>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-success">
              <i class="fas fa-donate text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has been deposited into your account!
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-warning">
              <i class="fas fa-exclamation-triangle text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We've noticed unusually high spending for your account.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
      </div>
    </li>

    <!-- Nav Item - Messages -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <!-- Counter - Messages -->
        <span class="badge badge-danger badge-counter">7</span>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
          Message Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div class="font-weight-bold">
            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
            <div class="small text-gray-500">Emily Fowler · 58m</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
            <div class="status-indicator"></div>
          </div>
          <div>
            <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
            <div class="small text-gray-500">Jae Chun · 1d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
            <div class="status-indicator bg-warning"></div>
          </div>
          <div>
            <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div>
            <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
            <div class="small text-gray-500">Chicken the Dog · 2w</div>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
      </div>
    </li> 

    <div class="topbar-divider d-none d-sm-block"></div>  %>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">My Profile</span>
        <%# <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60"> %>
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="<%= edit_registration_path(current_user) %>">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <!-- <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a> -->
        <div class="dropdown-divider"></div>
        <%= link_to fa_icon('sign-out-alt', text: 'Logout', class: 'fa-sm fa-fw mr-2 text-gray-400'), 
                    destroy_user_session_path,
                    method: :delete, 
                    class: 'dropdown-item' %>
      </div>
    </li>

  </ul>

</nav>
<!-- End of Topbar -->